version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./src:/var/www/html
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.dev.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    environment:
      - NGINX_ENV=development
  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8888:80
    environment:
      - PMA_HOST=db
      - PMA_USER=admin
      - PMA_PASSWORD=password

volumes:
  db-store: